# Generated by Django 5.0.3 on 2024-03-15 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_presentacion_aceptacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_presentacion_aceptacion.cliente'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_presentacion_aceptacion.oferta'),
        ),
    ]
