# Generated by Django 5.0.1 on 2024-03-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_presentacion_aceptacion', '0002_alter_tarjeta_cliente_alter_tarjeta_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='informacion_financiera',
        ),
        migrations.AddField(
            model_name='informacionfinanciera',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_presentacion_aceptacion.cliente'),
        ),
    ]
