# Generated by Django 5.0.1 on 2024-03-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_presentacion_aceptacion', '0003_remove_cliente_informacion_financiera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_presentacion_aceptacion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manejador_presentacion_aceptacion.solicitud'),
        ),
    ]
