# Generated by Django 4.2.11 on 2024-04-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_presentacion_aceptacion', '0005_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='manejador_presentacion_aceptacion.solicitud'),
        ),
    ]
